2025-08-24 22:44:40,584 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\utils\extractor.py changed, reloading.
2025-08-24 22:44:54,229 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\utils\extractor.py changed, reloading.
2025-08-24 22:46:13,622 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\utils\extractor.py changed, reloading.
2025-08-25 11:25:58,054 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 11:26:54,755 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\urls.py changed, reloading.
2025-08-25 11:29:44,860 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\urls.py changed, reloading.
2025-08-25 11:32:10,347 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor_project\urls.py changed, reloading.
2025-08-25 11:34:17,889 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\models.py changed, reloading.
2025-08-25 11:37:58,650 - ERROR - Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py", line 8, in dashboard_view
    return render(request, 'dashboard.html')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: dashboard.html
2025-08-25 11:43:30,274 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 11:44:29,895 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor_project\settings.py changed, reloading.
2025-08-25 11:44:35,665 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor_project\settings.py changed, reloading.
2025-08-25 12:01:03,195 - WARNING - Not Found: /media/uploads/DFIPL-WNEL-001-S1.pdf
2025-08-25 12:12:47,479 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 12:12:49,862 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 12:37:01,575 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor_project\urls.py changed, reloading.
2025-08-25 12:37:58,227 - ERROR - Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py", line 13, in dashboard
    return render(request, "dashboard.html", {"data": data})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: dashboard.html
2025-08-25 12:38:13,034 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor_project\urls.py changed, reloading.
2025-08-25 12:38:13,604 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor_project\urls.py changed, reloading.
2025-08-25 12:38:17,651 - ERROR - Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py", line 13, in dashboard
    return render(request, "dashboard.html", {"data": data})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: dashboard.html
2025-08-25 12:39:01,599 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 12:39:02,224 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 12:43:58,663 - ERROR - Internal Server Error: /upload/
Traceback (most recent call last):
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py", line 59, in upload_pdf
    extracted_info = extract_pdf_data(uploaded_pdf.file.path, vendor)
                     ^^^^^^^^^^^^^^^^
NameError: name 'extract_pdf_data' is not defined
2025-08-25 12:44:11,847 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 12:44:12,099 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 12:44:46,455 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 12:44:46,770 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 12:47:01,826 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 12:47:02,043 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 12:49:01,913 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor_project\settings.py changed, reloading.
2025-08-25 12:49:02,733 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor_project\settings.py changed, reloading.
2025-08-25 12:49:14,180 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor_project\urls.py changed, reloading.
2025-08-25 12:49:14,431 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor_project\urls.py changed, reloading.
2025-08-25 12:49:30,129 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\models.py changed, reloading.
2025-08-25 12:49:30,897 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\models.py changed, reloading.
2025-08-25 12:52:43,376 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor_project\settings.py changed, reloading.
2025-08-25 12:52:43,721 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor_project\settings.py changed, reloading.
2025-08-25 12:53:05,343 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\admin.py changed, reloading.
2025-08-25 12:53:05,430 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\admin.py changed, reloading.
2025-08-25 12:55:35,559 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor_project\settings.py changed, reloading.
2025-08-25 12:55:35,613 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor_project\settings.py changed, reloading.
2025-08-25 12:55:35,848 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor_project\settings.py changed, reloading.
2025-08-25 12:56:28,887 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor_project\urls.py changed, reloading.
2025-08-25 12:56:28,919 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor_project\settings.py changed, reloading.
2025-08-25 12:56:29,509 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\admin.py changed, reloading.
2025-08-25 12:59:41,688 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 12:59:41,715 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 12:59:42,269 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:00:08,116 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:00:09,096 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:00:09,143 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:00:18,644 - ERROR - Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py", line 18, in dashboard
    return render(request, "extractor/dashboard.html", {"data": data})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\base.py", line 481, in parse
    raise self.error(token, e)
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\base.py", line 693, in __init__
    filter_func = parser.find_filter(filter_name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\base.py", line 603, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'split'
2025-08-25 13:01:53,940 - ERROR - Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\defaulttags.py", line 1034, in find_library
    return parser.libraries[name]
           ~~~~~~~~~~~~~~~~^^^^^^
KeyError: 'extractor_filters'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py", line 18, in dashboard
    return render(request, "extractor/dashboard.html", {"data": data})
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\backends\django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\base.py", line 510, in parse
    raise self.error(token, e)
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\defaulttags.py", line 1096, in load
    lib = find_library(parser, name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mayank\Desktop\DEE\.venv\Lib\site-packages\django\template\defaulttags.py", line 1036, in find_library
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: 'extractor_filters' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
jazzmin
l10n
log
static
tz
2025-08-25 13:02:12,257 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\templatetags\extractor_filters.py changed, reloading.
2025-08-25 13:02:12,299 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\templatetags\extractor_filters.py changed, reloading.
2025-08-25 13:02:12,399 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\templatetags\extractor_filters.py changed, reloading.
2025-08-25 13:35:32,492 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:35:33,358 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:35:33,385 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:35:46,770 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:35:46,920 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:35:46,944 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:36:14,708 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:36:15,492 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:36:15,508 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:40:36,170 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:40:36,218 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:40:36,277 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:40:51,721 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:40:52,076 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:40:52,076 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:41:12,473 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:41:13,199 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:41:13,217 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:42:52,174 - ERROR - Vendor config not found at: C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\vendor_configs\jsw.json
2025-08-25 13:42:52,174 - ERROR - Error loading vendor config: ['Vendor configuration file not found for JSW']
2025-08-25 13:44:29,586 - ERROR - Vendor config not found at: C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\vendor_configs\jsw.json
2025-08-25 13:44:29,586 - ERROR - Error loading vendor config: ['Vendor configuration file not found for JSW']
2025-08-25 13:45:06,096 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:45:06,156 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:45:06,169 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:45:06,448 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:45:24,560 - ERROR - Vendor config not found at: C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\vendor_configs\jsw.json
2025-08-25 13:45:24,560 - ERROR - Error loading vendor config: ['Vendor configuration file not found for JSW']
2025-08-25 13:46:15,973 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:46:16,621 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:46:16,634 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:46:16,651 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:48:19,127 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:48:20,060 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:48:20,271 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:48:20,300 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:49:39,264 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:49:39,904 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:49:40,361 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:50:53,737 - ERROR - Vendor config not found at: C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\vendor_configs\jsw.json
2025-08-25 13:50:53,739 - ERROR - Error loading vendor config: ['Vendor configuration file not found for JSW']
2025-08-25 13:53:46,956 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:53:47,035 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:53:47,083 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:53:57,299 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\utils\extractor.py changed, reloading.
2025-08-25 13:53:57,416 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\utils\extractor.py changed, reloading.
2025-08-25 13:53:57,559 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\utils\extractor.py changed, reloading.
2025-08-25 13:55:11,513 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:55:12,337 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:55:12,339 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\views.py changed, reloading.
2025-08-25 13:55:20,635 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\utils\extractor.py changed, reloading.
2025-08-25 13:55:20,651 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\utils\extractor.py changed, reloading.
2025-08-25 13:55:20,949 - INFO - C:\Users\Mayank\Desktop\DEE\extractor_project\extractor\utils\extractor.py changed, reloading.
2025-08-25 13:56:33,919 - extractor - ERROR - Vendor config not found. Available configs: ['citic_steel.json', 'hengrum_steel.json', 'iraeta_steel.json', 'jsw_steel.json', 'posco_steel.json', 'citic_steel.json', 'jsw_steel.json']
2025-08-25 13:56:33,924 - extractor - ERROR - Error loading vendor config: ['Vendor configuration file not found for JSW']
2025-08-25 13:57:22,135 - extractor - ERROR - Vendor config not found. Available configs: ['citic_steel.json', 'hengrum_steel.json', 'iraeta_steel.json', 'jsw_steel.json', 'posco_steel.json', 'citic_steel.json', 'jsw_steel.json']
2025-08-25 13:57:22,137 - extractor - ERROR - Error loading vendor config: ['Vendor configuration file not found for JSW']
2025-08-25 14:18:38,180 - extractor - ERROR - Vendor config not found. Available configs: ['citic_steel.json', 'hengrum_steel.json', 'iraeta_steel.json', 'jsw_steel.json', 'posco_steel.json', 'citic_steel.json', 'jsw_steel.json']
2025-08-25 14:18:38,182 - extractor - ERROR - Error loading vendor config: ['Vendor configuration file not found for JSW']
2025-08-25 15:23:42,827 - extractor - ERROR - Vendor config not found. Available configs: ['citic_steel.json', 'hengrum_steel.json', 'iraeta_steel.json', 'jsw_steel.json', 'posco_steel.json', 'citic_steel.json', 'citic_steel_d6XAAlc.json', 'jsw_steel.json', 'jsw_steel_EnVeRuy.json']
2025-08-25 15:23:42,832 - extractor - ERROR - Error loading vendor config: ['Vendor configuration file not found for JSW']
2025-08-25 16:47:47,935 - extractor - ERROR - Error loading vendor config: ['Invalid vendor config: missing patterns for PLATE_NO, TEST_CERT_NO']
2025-08-25 16:48:10,678 - extractor - ERROR - Error loading vendor config: ['Invalid vendor config: missing patterns for PLATE_NO, TEST_CERT_NO']
2025-08-25 16:50:16,385 - extractor - ERROR - Error loading vendor config: ['Invalid vendor config: missing patterns for PLATE_NO, TEST_CERT_NO']
2025-08-26 16:26:30,105 - extractor.utils.extractor - ERROR - Missing vendor_id or vendor_name in config
2025-08-26 16:26:30,109 - extractor.tasks - ERROR - Error processing PDF: Invalid vendor configuration: missing vendor_id or vendor_name
Traceback (most recent call last):
  File "/code/extractor/tasks.py", line 21, in process_pdf_file
    extracted_data = extract_pdf_fields(
                     ^^^^^^^^^^^^^^^^^^^
  File "/code/extractor/utils/extractor.py", line 157, in extract_pdf_fields
    return extract_multi_entries(pdf_path, vendor_config, output_folder)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/extractor/utils/extractor.py", line 88, in extract_multi_entries
    raise ValueError("Invalid vendor configuration: missing vendor_id or vendor_name")
ValueError: Invalid vendor configuration: missing vendor_id or vendor_name
2025-08-27 19:00:53,765 - extractor.tasks - ERROR - Error processing PDF: insert or update on table "extractor_extracteddata" violates foreign key constraint "extractor_extractedd_pdf_id_83f6658e_fk_extractor"
DETAIL:  Key (pdf_id)=(8) is not present in table "extractor_uploadedpdf".
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.ForeignKeyViolation: insert or update on table "extractor_extracteddata" violates foreign key constraint "extractor_extractedd_pdf_id_83f6658e_fk_extractor"
DETAIL:  Key (pdf_id)=(8) is not present in table "extractor_uploadedpdf".


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/extractor/tasks.py", line 36, in process_pdf_file
    ExtractedData.objects.create(
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1071, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1112, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: insert or update on table "extractor_extracteddata" violates foreign key constraint "extractor_extractedd_pdf_id_83f6658e_fk_extractor"
DETAIL:  Key (pdf_id)=(8) is not present in table "extractor_uploadedpdf".

2025-08-29 11:25:05,589 - extractor - ERROR - Error loading vendor config: ['Invalid vendor config: missing patterns for PLATE_NO, TEST_CERT_NO']
2025-08-29 11:25:17,733 - extractor - ERROR - Error loading vendor config: ['Invalid vendor config: missing patterns for PLATE_NO, TEST_CERT_NO']
2025-08-29 11:25:29,068 - extractor - ERROR - Error loading vendor config: ['Invalid vendor config: missing patterns for PLATE_NO, TEST_CERT_NO']
2025-08-29 11:25:54,356 - extractor - ERROR - Error loading vendor config: ['Invalid vendor config: missing patterns for PLATE_NO, TEST_CERT_NO']
2025-08-29 11:26:03,476 - extractor - ERROR - Error loading vendor config: ['Invalid vendor config: missing patterns for PLATE_NO, TEST_CERT_NO']
2025-08-29 11:29:44,484 - extractor - ERROR - Error loading vendor config: ['Invalid vendor config: missing patterns for PLATE_NO, TEST_CERT_NO']
2025-08-29 11:29:52,132 - extractor - ERROR - Error loading vendor config: ['Invalid vendor config: missing patterns for TEST_CERT_NO']
2025-08-29 11:30:00,203 - extractor - ERROR - Error loading vendor config: ['Invalid vendor config: missing patterns for TEST_CERT_NO']
2025-08-29 11:34:03,179 - extractor - ERROR - Error loading vendor config: ['Invalid vendor config: missing patterns for PLATE_NO, TEST_CERT_NO']
2025-08-29 15:15:00,986 - INFO - Processing PDF upload request
2025-08-29 15:15:00,997 - DEBUG - Received vendor_id: 1
2025-08-29 15:15:00,999 - DEBUG - Received file: DFIPL-WNEL-001-S1.pdf
2025-08-29 15:15:01,137 - INFO - Loading config for vendor: jsw
2025-08-29 15:15:01,139 - INFO - Using config file: /code/extractor/vendor_configs/jsw_steel.json
2025-08-29 15:15:01,142 - INFO - Successfully loaded vendor config: {'vendor_id': 'jsw', 'vendor_name': 'JSW Steel', 'fields': {'PLATE_NO': '\\b\\d{2}[A-Z]{2}\\d{4}[A-Z]\\d\\b', 'HEAT_NO': '\\b[A-Z]\\d{6}\\b', 'TEST_CERT_NO': 'TEST CERTIFICATE NO\\.\\s*:\\s*([A-Z0-9\\/\\-]+)'}}
2025-08-29 15:15:01,143 - INFO - === Starting Extraction Process ===
2025-08-29 15:15:01,143 - INFO - PDF Path: /code/media/uploads/DFIPL-WNEL-001-S1_qWhbvUf.pdf
2025-08-29 15:15:01,144 - INFO - Vendor: JSW Steel
2025-08-29 15:15:01,145 - INFO - Vendor Config: {'vendor_id': 'jsw', 'vendor_name': 'JSW Steel', 'fields': {'PLATE_NO': '\\b\\d{2}[A-Z]{2}\\d{4}[A-Z]\\d\\b', 'HEAT_NO': '\\b[A-Z]\\d{6}\\b', 'TEST_CERT_NO': 'TEST CERTIFICATE NO\\.\\s*:\\s*([A-Z0-9\\/\\-]+)'}}
2025-08-29 15:15:01,148 - INFO - File size: 13184794 bytes
2025-08-29 15:15:01,152 - INFO - Output directory ready: /code/media/extracted
2025-08-29 15:15:01,153 - INFO - Queueing extraction task...
2025-08-29 15:15:01,209 - INFO - Extraction task queued with ID: 7d387678-df08-472c-a5d0-4c44ab18e06d
2025-08-29 15:15:01,939 - extractor.utils.extractor - ERROR - Error processing page 2 in /code/media/uploads/DFIPL-WNEL-001-S1_qWhbvUf.pdf: 'NoneType' object has no attribute 'replace'
2025-08-29 15:15:29,479 - extractor.utils.extractor - ERROR - Error processing page 22 in /code/media/uploads/DFIPL-WNEL-001-S1_qWhbvUf.pdf: 'NoneType' object has no attribute 'replace'
2025-08-29 15:15:29,631 - extractor.utils.extractor - ERROR - Error processing page 23 in /code/media/uploads/DFIPL-WNEL-001-S1_qWhbvUf.pdf: 'NoneType' object has no attribute 'replace'
2025-08-29 15:18:47,206 - INFO - Processing PDF upload request
2025-08-29 15:18:47,208 - DEBUG - Received vendor_id: 4
2025-08-29 15:18:47,210 - DEBUG - Received file: Binder1.pdf
2025-08-29 15:18:47,361 - INFO - Loading config for vendor: citic
2025-08-29 15:18:47,366 - INFO - Using config file: /code/extractor/vendor_configs/citic_steel.json
2025-08-29 15:18:47,373 - INFO - Successfully loaded vendor config: {'vendor_id': 'citic', 'vendor_name': 'CITIC Pacific Special Steel', 'fields': {'PLATE_NO': '\\bT5\\d{9}\\b', 'HEAT_NO': '\\bS\\d{6,10}\\b', 'TEST_CERT_NO': '\\bZ\\d{15,18}\\b'}}
2025-08-29 15:18:47,374 - INFO - === Starting Extraction Process ===
2025-08-29 15:18:47,376 - INFO - PDF Path: /code/media/uploads/Binder1_cSyyHlg.pdf
2025-08-29 15:18:47,377 - INFO - Vendor: CITIC Steel
2025-08-29 15:18:47,378 - INFO - Vendor Config: {'vendor_id': 'citic', 'vendor_name': 'CITIC Pacific Special Steel', 'fields': {'PLATE_NO': '\\bT5\\d{9}\\b', 'HEAT_NO': '\\bS\\d{6,10}\\b', 'TEST_CERT_NO': '\\bZ\\d{15,18}\\b'}}
2025-08-29 15:18:47,385 - INFO - File size: 12639122 bytes
2025-08-29 15:18:47,391 - INFO - Output directory ready: /code/media/extracted
2025-08-29 15:18:47,392 - INFO - Queueing extraction task...
2025-08-29 15:18:47,395 - INFO - Extraction task queued with ID: e471a608-a607-4bfd-807a-7a336d9f3867
2025-08-29 15:30:49,268 - INFO - Processing PDF upload request
2025-08-29 15:30:49,291 - DEBUG - Received vendor_id: 7
2025-08-29 15:30:49,293 - DEBUG - Received file: MTC-1-80.pdf
2025-08-29 15:30:49,526 - INFO - Loading config for vendor: posco
2025-08-29 15:30:49,529 - INFO - Using config file: /code/extractor/vendor_configs/posco_steel.json
2025-08-29 15:30:49,537 - INFO - Successfully loaded vendor config: {'vendor_id': 'posco', 'vendor_name': 'POSCO International Corporation', 'fields': {'PLATE_NO': '\\bPP\\d{8,12}(?:-\\d+)?\\b', 'HEAT_NO': '\\bSU\\d{5,8}\\b', 'TEST_CERT_NO': '(?i)\\b\\d{6}-FP\\d{2}[A-Z]{2}-\\d{4}[A-Z]\\d-\\d{4}\\b'}}
2025-08-29 15:30:49,538 - INFO - === Starting Extraction Process ===
2025-08-29 15:30:49,540 - INFO - PDF Path: /code/media/uploads/MTC-1-80_RWUVKlH.pdf
2025-08-29 15:30:49,542 - INFO - Vendor: Posco Steel
2025-08-29 15:30:49,544 - INFO - Vendor Config: {'vendor_id': 'posco', 'vendor_name': 'POSCO International Corporation', 'fields': {'PLATE_NO': '\\bPP\\d{8,12}(?:-\\d+)?\\b', 'HEAT_NO': '\\bSU\\d{5,8}\\b', 'TEST_CERT_NO': '(?i)\\b\\d{6}-FP\\d{2}[A-Z]{2}-\\d{4}[A-Z]\\d-\\d{4}\\b'}}
2025-08-29 15:30:49,553 - INFO - File size: 19812918 bytes
2025-08-29 15:30:49,559 - INFO - Output directory ready: /code/media/extracted
2025-08-29 15:30:49,561 - INFO - Queueing extraction task...
2025-08-29 15:30:49,571 - INFO - Extraction task queued with ID: be46709b-0b21-478a-9342-7ff4ecfe2770
2025-08-29 15:31:40,378 - INFO - Processing PDF upload request
2025-08-29 15:31:40,381 - DEBUG - Received vendor_id: 7
2025-08-29 15:31:40,382 - DEBUG - Received file: MTC-1-80.pdf
2025-08-29 15:31:40,599 - INFO - Loading config for vendor: posco
2025-08-29 15:31:40,603 - INFO - Using config file: /code/extractor/vendor_configs/posco_steel.json
2025-08-29 15:31:40,609 - INFO - Successfully loaded vendor config: {'vendor_id': 'posco', 'vendor_name': 'POSCO International Corporation', 'fields': {'PLATE_NO': '\\bPP\\d{8,12}(?:-\\d+)?\\b', 'HEAT_NO': '\\bSU\\d{5,8}\\b', 'TEST_CERT_NO': '(?i)\\b\\d{6}-FP\\d{2}[A-Z]{2}-\\d{4}[A-Z]\\d-\\d{4}\\b'}}
2025-08-29 15:31:40,610 - INFO - === Starting Extraction Process ===
2025-08-29 15:31:40,612 - INFO - PDF Path: /code/media/uploads/MTC-1-80_aCKlAKS.pdf
2025-08-29 15:31:40,613 - INFO - Vendor: Posco Steel
2025-08-29 15:31:40,615 - INFO - Vendor Config: {'vendor_id': 'posco', 'vendor_name': 'POSCO International Corporation', 'fields': {'PLATE_NO': '\\bPP\\d{8,12}(?:-\\d+)?\\b', 'HEAT_NO': '\\bSU\\d{5,8}\\b', 'TEST_CERT_NO': '(?i)\\b\\d{6}-FP\\d{2}[A-Z]{2}-\\d{4}[A-Z]\\d-\\d{4}\\b'}}
2025-08-29 15:31:40,618 - INFO - File size: 19812918 bytes
2025-08-29 15:31:40,622 - INFO - Output directory ready: /code/media/extracted
2025-08-29 15:31:40,624 - INFO - Queueing extraction task...
2025-08-29 15:31:40,631 - INFO - Extraction task queued with ID: 62b85742-2666-4635-a509-ff4b8448702f
2025-08-29 15:32:07,944 - extractor.utils.extractor - ERROR - Error processing page 10 in /code/media/uploads/MTC-1-80_RWUVKlH.pdf: 
2025-08-29 15:32:22,438 - extractor.utils.extractor - ERROR - Error processing page 7 in /code/media/uploads/MTC-1-80_aCKlAKS.pdf: File is not a zip file
2025-08-29 16:33:19,547 - INFO - /code/extractor/utils/extractor.py changed, reloading.
2025-08-29 16:37:10,910 - INFO - Processing PDF upload request
2025-08-29 16:37:10,916 - DEBUG - Received vendor_id: 7
2025-08-29 16:37:10,917 - DEBUG - Received file: MTC-1-80-73.pdf
2025-08-29 16:37:10,972 - INFO - Loading config for vendor: posco
2025-08-29 16:37:10,977 - INFO - Using config file: /code/extractor/vendor_configs/posco_steel.json
2025-08-29 16:37:10,983 - INFO - Successfully loaded vendor config: {'vendor_id': 'posco', 'vendor_name': 'POSCO International Corporation', 'fields': {'PLATE_NO': '\\bPP\\d{8,12}(?:-\\d+)?\\b', 'HEAT_NO': '\\bSU\\d{5,8}\\b', 'TEST_CERT_NO': '(?i)\\b\\d{6}-FP\\d{2}[A-Z]{2}-\\d{4}[A-Z]\\d-\\d{4}\\b'}}
2025-08-29 16:37:10,985 - INFO - === Starting Extraction Process ===
2025-08-29 16:37:10,986 - INFO - PDF Path: /code/media/uploads/MTC-1-80-73.pdf
2025-08-29 16:37:10,987 - INFO - Vendor: Posco Steel
2025-08-29 16:37:10,991 - INFO - Vendor Config: {'vendor_id': 'posco', 'vendor_name': 'POSCO International Corporation', 'fields': {'PLATE_NO': '\\bPP\\d{8,12}(?:-\\d+)?\\b', 'HEAT_NO': '\\bSU\\d{5,8}\\b', 'TEST_CERT_NO': '(?i)\\b\\d{6}-FP\\d{2}[A-Z]{2}-\\d{4}[A-Z]\\d-\\d{4}\\b'}}
2025-08-29 16:37:10,998 - INFO - File size: 473440 bytes
2025-08-29 16:37:11,003 - INFO - Output directory ready: /code/media/extracted
2025-08-29 16:37:11,004 - INFO - Queueing extraction task...
2025-08-29 16:37:11,070 - INFO - Extraction task queued with ID: 15019dea-ac57-4f69-a64c-2c895179935f
2025-08-29 16:40:34,381 - INFO - Processing PDF upload request
2025-08-29 16:40:34,386 - DEBUG - Received vendor_id: 7
2025-08-29 16:40:34,387 - DEBUG - Received file: MTC-1-80-49.pdf
2025-08-29 16:40:34,429 - INFO - Loading config for vendor: posco
2025-08-29 16:40:34,434 - INFO - Using config file: /code/extractor/vendor_configs/posco_steel.json
2025-08-29 16:40:34,438 - INFO - Successfully loaded vendor config: {'vendor_id': 'posco', 'vendor_name': 'POSCO International Corporation', 'fields': {'PLATE_NO': '\\bPP\\d{8,12}(?:-\\d+)?\\b', 'HEAT_NO': '\\bSU\\d{5,8}\\b', 'TEST_CERT_NO': '(?i)\\b\\d{6}-FP\\d{2}[A-Z]{2}-\\d{4}[A-Z]\\d-\\d{4}\\b'}}
2025-08-29 16:40:34,440 - INFO - === Starting Extraction Process ===
2025-08-29 16:40:34,441 - INFO - PDF Path: /code/media/uploads/MTC-1-80-49.pdf
2025-08-29 16:40:34,441 - INFO - Vendor: Posco Steel
2025-08-29 16:40:34,442 - INFO - Vendor Config: {'vendor_id': 'posco', 'vendor_name': 'POSCO International Corporation', 'fields': {'PLATE_NO': '\\bPP\\d{8,12}(?:-\\d+)?\\b', 'HEAT_NO': '\\bSU\\d{5,8}\\b', 'TEST_CERT_NO': '(?i)\\b\\d{6}-FP\\d{2}[A-Z]{2}-\\d{4}[A-Z]\\d-\\d{4}\\b'}}
2025-08-29 16:40:34,446 - INFO - File size: 471014 bytes
2025-08-29 16:40:34,449 - INFO - Output directory ready: /code/media/extracted
2025-08-29 16:40:34,451 - INFO - Queueing extraction task...
2025-08-29 16:40:34,454 - INFO - Extraction task queued with ID: 4106403a-74e8-451e-9a39-0171e3b11c22
2025-08-29 16:40:53,666 - INFO - /code/extractor/utils/extractor.py changed, reloading.
2025-08-29 16:41:15,232 - INFO - Processing PDF upload request
2025-08-29 16:41:15,239 - DEBUG - Received vendor_id: 7
2025-08-29 16:41:15,242 - DEBUG - Received file: MTC-1-80-49.pdf
2025-08-29 16:41:15,328 - INFO - Loading config for vendor: posco
2025-08-29 16:41:15,338 - INFO - Using config file: /code/extractor/vendor_configs/posco_steel.json
2025-08-29 16:41:15,350 - INFO - Successfully loaded vendor config: {'vendor_id': 'posco', 'vendor_name': 'POSCO International Corporation', 'fields': {'PLATE_NO': '\\bPP\\d{8,12}(?:-\\d+)?\\b', 'HEAT_NO': '\\bSU\\d{5,8}\\b', 'TEST_CERT_NO': '(?i)\\b\\d{6}-FP\\d{2}[A-Z]{2}-\\d{4}[A-Z]\\d-\\d{4}\\b'}}
2025-08-29 16:41:15,353 - INFO - === Starting Extraction Process ===
2025-08-29 16:41:15,356 - INFO - PDF Path: /code/media/uploads/MTC-1-80-49_p2s9THk.pdf
2025-08-29 16:41:15,358 - INFO - Vendor: Posco Steel
2025-08-29 16:41:15,360 - INFO - Vendor Config: {'vendor_id': 'posco', 'vendor_name': 'POSCO International Corporation', 'fields': {'PLATE_NO': '\\bPP\\d{8,12}(?:-\\d+)?\\b', 'HEAT_NO': '\\bSU\\d{5,8}\\b', 'TEST_CERT_NO': '(?i)\\b\\d{6}-FP\\d{2}[A-Z]{2}-\\d{4}[A-Z]\\d-\\d{4}\\b'}}
2025-08-29 16:41:15,375 - INFO - File size: 471014 bytes
2025-08-29 16:41:15,389 - INFO - Output directory ready: /code/media/extracted
2025-08-29 16:41:15,392 - INFO - Queueing extraction task...
2025-08-29 16:41:15,459 - INFO - Extraction task queued with ID: 46ba438e-bd53-48c2-8244-9c6c44749dcd
2025-08-30 12:25:22,397 - WARNING - Not Found: /favicon.ico
2025-08-30 12:27:07,014 - INFO - Processing PDF upload request
2025-08-30 12:27:07,020 - DEBUG - Received vendor_id: 1
2025-08-30 12:27:07,022 - DEBUG - Received file: DFIPL-WNEL-001-S1-3-9.pdf
2025-08-30 12:27:07,072 - INFO - Loading config for vendor: jsw
2025-08-30 12:27:07,076 - INFO - Using config file: /code/extractor/vendor_configs/jsw_steel.json
2025-08-30 12:27:07,081 - INFO - Successfully loaded vendor config.
2025-08-30 12:27:07,082 - INFO - Queueing extraction task...
2025-08-30 12:27:07,140 - INFO - Extraction task queued with ID: 43b5f809-21ea-4fe7-a8b8-1cad80e72ced
2025-08-30 12:40:42,699 - INFO - Processing PDF upload request
2025-08-30 12:40:42,702 - DEBUG - Received vendor_id: 1
2025-08-30 12:40:42,703 - DEBUG - Received file: DFIPL-WNEL-001-S1.pdf
2025-08-30 12:40:42,878 - INFO - Loading config for vendor: jsw
2025-08-30 12:40:42,881 - INFO - Using config file: /code/extractor/vendor_configs/jsw_steel.json
2025-08-30 12:40:42,885 - INFO - Successfully loaded vendor config.
2025-08-30 12:40:42,885 - INFO - Queueing extraction task...
2025-08-30 12:40:42,891 - INFO - Extraction task queued with ID: ef3c4927-9eac-4982-9493-cc5c72a6a755
2025-08-30 12:40:43,862 - extractor.utils.extractor - ERROR - Error processing page 2 in /code/media/uploads/DFIPL-WNEL-001-S1_fBkYKZp.pdf: 'NoneType' object has no attribute 'replace'
2025-08-30 12:41:19,314 - extractor.utils.extractor - ERROR - Error processing page 22 in /code/media/uploads/DFIPL-WNEL-001-S1_fBkYKZp.pdf: 'NoneType' object has no attribute 'replace'
2025-08-30 12:41:19,668 - extractor.utils.extractor - ERROR - Error processing page 23 in /code/media/uploads/DFIPL-WNEL-001-S1_fBkYKZp.pdf: 'NoneType' object has no attribute 'replace'
2025-08-30 12:42:00,139 - INFO - Processing PDF upload request
2025-08-30 12:42:00,140 - DEBUG - Received vendor_id: 1
2025-08-30 12:42:00,141 - DEBUG - Received file: DFIPL-WNEL-001-S1.pdf
2025-08-30 12:42:00,261 - INFO - Loading config for vendor: jsw
2025-08-30 12:42:00,263 - INFO - Using config file: /code/extractor/vendor_configs/jsw_steel.json
2025-08-30 12:42:00,267 - INFO - Successfully loaded vendor config.
2025-08-30 12:42:00,267 - INFO - Queueing extraction task...
2025-08-30 12:42:00,270 - INFO - Extraction task queued with ID: 274e6c5c-6cca-410e-b0a7-06fbf71eddea
2025-08-30 12:42:01,031 - extractor.utils.extractor - ERROR - Error processing page 2 in /code/media/uploads/DFIPL-WNEL-001-S1_U6N30vX.pdf: 'NoneType' object has no attribute 'replace'
2025-08-30 12:42:33,738 - extractor.utils.extractor - ERROR - Error processing page 22 in /code/media/uploads/DFIPL-WNEL-001-S1_U6N30vX.pdf: 'NoneType' object has no attribute 'replace'
2025-08-30 12:42:33,883 - extractor.utils.extractor - ERROR - Error processing page 23 in /code/media/uploads/DFIPL-WNEL-001-S1_U6N30vX.pdf: 'NoneType' object has no attribute 'replace'
2025-08-30 13:48:55,810 - ERROR - Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/extractor/views.py", line 341, in dashboard
    return render(request, "extractor/dashboard.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 481, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' No' from 'row.Sr No'
2025-08-30 13:48:56,054 - WARNING - Not Found: /favicon.ico
2025-08-30 13:50:54,611 - ERROR - Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/extractor/views.py", line 341, in dashboard
    return render(request, "extractor/dashboard.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 481, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' PDF' from 'row.Source PDF'
2025-08-30 13:50:54,796 - WARNING - Not Found: /favicon.ico
2025-08-30 13:50:57,125 - ERROR - Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/extractor/views.py", line 341, in dashboard
    return render(request, "extractor/dashboard.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/backends/django.py", line 33, in get_template
    return Template(self.engine.get_template(template_name), self)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/engine.py", line 177, in get_template
    template, origin = self.find_template(template_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/engine.py", line 159, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/loaders/cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/loaders/base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 196, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/defaulttags.py", line 961, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 510, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 508, in parse
    compiled_result = compile_func(self, token)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/defaulttags.py", line 861, in do_for
    nodelist_loop = parser.parse(
                    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 481, in parse
    raise self.error(token, e)
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 479, in parse
    filter_expression = self.compile_filter(token.contents)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 597, in compile_filter
    return FilterExpression(token, self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 698, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' PDF' from 'row.Source PDF'
2025-08-30 13:50:57,281 - WARNING - Not Found: /favicon.ico
2025-08-30 13:52:02,729 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 13:52:06,378 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 13:52:20,131 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 13:52:25,247 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 13:52:31,829 - WARNING - Not Found: /favicon.ico
2025-08-30 13:52:40,382 - ERROR - Internal Server Error: /upload/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view extractor.views.upload_pdf didn't return an HttpResponse object. It returned None instead.
2025-08-30 13:55:35,921 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 13:55:39,643 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 13:57:33,028 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 13:57:37,952 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 13:57:42,045 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 13:59:24,739 - WARNING - Not Found: /favicon.ico
2025-08-30 13:59:26,776 - WARNING - Not Found: /favicon.ico
2025-08-30 13:59:27,063 - WARNING - Not Found: /favicon.ico
2025-08-30 13:59:27,370 - WARNING - Not Found: /favicon.ico
2025-08-30 13:59:27,667 - WARNING - Not Found: /favicon.ico
2025-08-30 13:59:29,019 - WARNING - Not Found: /favicon.ico
2025-08-30 13:59:30,435 - WARNING - Not Found: /favicon.ico
2025-08-30 13:59:30,745 - WARNING - Not Found: /favicon.ico
2025-08-30 13:59:31,034 - WARNING - Not Found: /favicon.ico
2025-08-30 13:59:47,405 - WARNING - Not Found: /favicon.ico
2025-08-30 14:00:12,544 - WARNING - Not Found: /favicon.ico
2025-08-30 14:00:12,844 - WARNING - Not Found: /favicon.ico
2025-08-30 14:00:13,100 - WARNING - Not Found: /favicon.ico
2025-08-30 14:00:13,294 - WARNING - Not Found: /favicon.ico
2025-08-30 14:00:13,437 - WARNING - Not Found: /favicon.ico
2025-08-30 14:00:13,561 - WARNING - Not Found: /favicon.ico
2025-08-30 14:01:52,912 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:01:56,286 - ERROR - Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/extractor/views.py", line 96, in dashboard
    df = build_extracted_dataframe()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/extractor/views.py", line 68, in build_extracted_dataframe
    key = r.hash_value or f"{r.pdf_id}_{r.created_at.date()}"
          ^^^^^^^^^^^^
AttributeError: 'ExtractedData' object has no attribute 'hash_value'
2025-08-30 14:01:58,545 - ERROR - Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/extractor/views.py", line 96, in dashboard
    df = build_extracted_dataframe()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/extractor/views.py", line 68, in build_extracted_dataframe
    key = r.hash_value or f"{r.pdf_id}_{r.created_at.date()}"
          ^^^^^^^^^^^^
AttributeError: 'ExtractedData' object has no attribute 'hash_value'
2025-08-30 14:01:58,671 - WARNING - Not Found: /favicon.ico
2025-08-30 14:03:18,801 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:03:22,327 - WARNING - Not Found: /favicon.ico
2025-08-30 14:04:58,086 - ERROR - Internal Server Error: /upload/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 204, in _get_response
    self.check_response(response, callback)
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 332, in check_response
    raise ValueError(
ValueError: The view extractor.views.upload_pdf didn't return an HttpResponse object. It returned None instead.
2025-08-30 14:06:02,636 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:06:06,987 - WARNING - Not Found: /favicon.ico
2025-08-30 14:06:17,616 - ERROR - Internal Server Error: /upload/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.errors.NotNullViolation: null value in column "vendor_id" of relation "extractor_uploadedpdf" violates not-null constraint
DETAIL:  Failing row contains (107, /media/DFIPL-WNEL-001-S1_gNUeTEh.pdf, 2025-08-30 08:36:17.583202+00, null).


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/extractor/views.py", line 127, in upload_pdf
    uploaded_pdf = UploadedPDF.objects.create(file=fs.url(filename))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 679, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 822, in save
    self.save_base(
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 909, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1071, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/base.py", line 1112, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/models/sql/compiler.py", line 1823, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 122, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/site-packages/django/db/backends/utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.IntegrityError: null value in column "vendor_id" of relation "extractor_uploadedpdf" violates not-null constraint
DETAIL:  Failing row contains (107, /media/DFIPL-WNEL-001-S1_gNUeTEh.pdf, 2025-08-30 08:36:17.583202+00, null).

2025-08-30 14:07:11,154 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:07:16,195 - ERROR - Internal Server Error: /upload/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/extractor/views.py", line 142, in upload_pdf
    task = process_pdf_file.delay(uploaded_pdf.id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/task.py", line 444, in delay
    return self.apply_async(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/celery/app/task.py", line 559, in apply_async
    check_arguments(*(args or ()), **(kwargs or {}))
TypeError: process_pdf_file() missing 1 required positional argument: 'vendor_config'
2025-08-30 14:07:16,353 - WARNING - Not Found: /favicon.ico
2025-08-30 14:07:53,174 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:07:57,163 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:08:05,715 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:08:13,136 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:08:24,439 - ERROR - Internal Server Error: /upload/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/extractor/views.py", line 144, in upload_pdf
    # ✅ load vendor config
                   ^^^^^^^^^
  File "/code/extractor/utils/config_loader.py", line 7, in load_vendor_config
    raise FileNotFoundError(f"Config for vendor '{vendor_id}' not found.")
FileNotFoundError: Config for vendor 'JSW Steel' not found.
2025-08-30 14:08:24,589 - WARNING - Not Found: /favicon.ico
2025-08-30 14:12:27,463 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:12:31,679 - WARNING - Not Found: /favicon.ico
2025-08-30 14:14:46,496 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:14:52,152 - WARNING - Not Found: /favicon.ico
2025-08-30 14:15:17,124 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:15:20,180 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:15:25,698 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:15:37,873 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:16:48,672 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:17:04,677 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:17:17,684 - WARNING - Not Found: /favicon.ico
2025-08-30 14:17:20,216 - WARNING - Not Found: /favicon.ico
2025-08-30 14:17:34,563 - INFO - Processing PDF upload request
2025-08-30 14:17:34,567 - DEBUG - Received vendor_id: 1
2025-08-30 14:17:34,568 - DEBUG - Received file: DFIPL-WNEL-001-S1.pdf
2025-08-30 14:17:34,711 - INFO - Loading config for vendor: jsw
2025-08-30 14:17:34,715 - INFO - Using config file: /code/extractor/vendor_configs/jsw_steel.json
2025-08-30 14:17:34,719 - INFO - Successfully loaded vendor config.
2025-08-30 14:17:34,719 - INFO - Queueing extraction task...
2025-08-30 14:17:34,796 - INFO - Extraction task queued with ID: 98623346-f428-4cf6-baa8-0ef221f28846
2025-08-30 14:17:35,329 - extractor.utils.extractor - ERROR - Error processing page 2 in /code/media/uploads/DFIPL-WNEL-001-S1_wKWlHL9.pdf: 'NoneType' object has no attribute 'replace'
2025-08-30 14:18:00,804 - extractor.utils.extractor - ERROR - Error processing page 22 in /code/media/uploads/DFIPL-WNEL-001-S1_wKWlHL9.pdf: 'NoneType' object has no attribute 'replace'
2025-08-30 14:18:00,912 - extractor.utils.extractor - ERROR - Error processing page 23 in /code/media/uploads/DFIPL-WNEL-001-S1_wKWlHL9.pdf: 'NoneType' object has no attribute 'replace'
2025-08-30 14:24:06,225 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:24:35,861 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:24:45,117 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:25:10,979 - INFO - /code/extractor/tasks.py changed, reloading.
2025-08-30 14:25:14,766 - INFO - /code/extractor/tasks.py changed, reloading.
2025-08-30 14:25:21,876 - INFO - /code/extractor/tasks.py changed, reloading.
2025-08-30 14:25:41,890 - INFO - /code/extractor/tasks.py changed, reloading.
2025-08-30 14:25:48,224 - WARNING - Not Found: /favicon.ico
2025-08-30 14:25:58,386 - WARNING - Not Found: /favicon.ico
2025-08-30 14:27:36,951 - INFO - /code/extractor/tasks.py changed, reloading.
2025-08-30 14:29:24,584 - INFO - /code/extractor/tasks.py changed, reloading.
2025-08-30 14:29:31,708 - WARNING - Not Found: /favicon.ico
2025-08-30 14:35:55,880 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:38:19,798 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:38:34,037 - WARNING - Not Found: /favicon.ico
2025-08-30 14:38:37,434 - WARNING - Not Found: /favicon.ico
2025-08-30 14:39:00,414 - INFO - Processing PDF upload request
2025-08-30 14:39:00,416 - DEBUG - Received vendor_id: 1
2025-08-30 14:39:00,418 - DEBUG - Received file: DFIPL-WNEL-001-S1.pdf
2025-08-30 14:39:00,549 - INFO - Loading config for vendor: jsw
2025-08-30 14:39:00,551 - INFO - Using config file: /code/extractor/vendor_configs/jsw_steel.json
2025-08-30 14:39:00,556 - INFO - Successfully loaded vendor config.
2025-08-30 14:39:00,558 - INFO - Queueing extraction task...
2025-08-30 14:39:00,675 - INFO - Extraction task queued with ID: b4d5ddeb-44d7-4b24-b550-503676a377dd
2025-08-30 14:39:01,253 - extractor.utils.extractor - ERROR - Error processing page 2 in /code/media/uploads/DFIPL-WNEL-001-S1_P6756TC.pdf: 'NoneType' object has no attribute 'replace'
2025-08-30 14:39:24,881 - extractor.utils.extractor - ERROR - Error processing page 22 in /code/media/uploads/DFIPL-WNEL-001-S1_P6756TC.pdf: 'NoneType' object has no attribute 'replace'
2025-08-30 14:39:24,987 - extractor.utils.extractor - ERROR - Error processing page 23 in /code/media/uploads/DFIPL-WNEL-001-S1_P6756TC.pdf: 'NoneType' object has no attribute 'replace'
2025-08-30 14:39:32,124 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:39:50,462 - INFO - Processing PDF upload request
2025-08-30 14:39:50,467 - DEBUG - Received vendor_id: 1
2025-08-30 14:39:50,468 - DEBUG - Received file: DFIPL-WNEL-001-S1.pdf
2025-08-30 14:39:50,594 - INFO - Loading config for vendor: jsw
2025-08-30 14:39:50,597 - INFO - Using config file: /code/extractor/vendor_configs/jsw_steel.json
2025-08-30 14:39:50,602 - INFO - Successfully loaded vendor config.
2025-08-30 14:39:50,603 - INFO - Queueing extraction task...
2025-08-30 14:39:50,655 - INFO - Extraction task queued with ID: 24937a1e-5df5-4e60-8588-9d22f349d06a
2025-08-30 14:39:51,305 - extractor.utils.extractor - ERROR - Error processing page 2 in /code/media/uploads/DFIPL-WNEL-001-S1_sBh4WNt.pdf: 'NoneType' object has no attribute 'replace'
2025-08-30 14:40:16,221 - extractor.utils.extractor - ERROR - Error processing page 22 in /code/media/uploads/DFIPL-WNEL-001-S1_sBh4WNt.pdf: 'NoneType' object has no attribute 'replace'
2025-08-30 14:40:16,338 - extractor.utils.extractor - ERROR - Error processing page 23 in /code/media/uploads/DFIPL-WNEL-001-S1_sBh4WNt.pdf: 'NoneType' object has no attribute 'replace'
2025-08-30 14:46:02,632 - INFO - /code/extractor/views.py changed, reloading.
2025-08-30 14:46:08,216 - WARNING - Not Found: /favicon.ico
2025-08-30 14:46:20,434 - INFO - Processing PDF upload request
2025-08-30 14:51:44,652 - WARNING - Not Found: /favicon.ico
2025-08-30 14:51:46,254 - WARNING - Not Found: /favicon.ico
2025-08-30 14:51:55,061 - INFO - Processing PDF upload request
2025-08-30 14:51:55,778 - extractor.utils.extractor - ERROR - Error processing page 2 in /code/media/uploads/DFIPL-WNEL-001-S1_5uLfbGy.pdf: 'NoneType' object has no attribute 'replace'
2025-08-30 14:52:19,543 - extractor.utils.extractor - ERROR - Error processing page 22 in /code/media/uploads/DFIPL-WNEL-001-S1_5uLfbGy.pdf: 'NoneType' object has no attribute 'replace'
2025-08-30 14:52:19,812 - extractor.utils.extractor - ERROR - Error processing page 23 in /code/media/uploads/DFIPL-WNEL-001-S1_5uLfbGy.pdf: 'NoneType' object has no attribute 'replace'
2025-08-31 22:06:50,512 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 22:07:00,696 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 22:10:43,217 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 22:22:33,109 - ERROR - Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 875, in _resolve_lookup
    current = current[bit]
              ~~~~~~~^^^^^
KeyError: 'Source_PDF'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
              ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'Source_PDF'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 891, in _resolve_lookup
    current = current[int(bit)]
                      ^^^^^^^^
ValueError: invalid literal for int() with base 10: 'Source_PDF'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/extractor/views.py", line 79, in dashboard
    return render(request, "extractor/dashboard.html", context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 163, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/defaulttags.py", line 326, in render
    return nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/defaulttags.py", line 242, in render
    nodelist.append(node.render_annotated(context))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 961, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 731, in resolve
    arg_vals.append(arg.resolve(context))
                    ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 842, in resolve
    value = self._resolve_lookup(context)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/django/template/base.py", line 898, in _resolve_lookup
    raise VariableDoesNotExist(
django.template.base.VariableDoesNotExist: Failed lookup for key [Source_PDF] in {'Vendor': 'JSW Steel', 'PLATE_NO': '24LP1615A1', 'HEAT_NO': nan, 'TEST_CERT_NO': nan, 'Filename': 'DFIPL-WNEL-001-S1_wKWlHL9.pdf', 'Page': nan, 'Source PDF': 'DFIPL-WNEL-001-S1_wKWlHL9.pdf', 'Created': '2025-08-30 14:18:41'}
2025-08-31 22:22:33,545 - WARNING - Not Found: /favicon.ico
2025-08-31 22:23:45,091 - INFO - /code/extractor/templatetags/extractor_filters.py changed, reloading.
2025-08-31 22:24:21,569 - INFO - /code/extractor/templatetags/extractor_filters.py changed, reloading.
2025-08-31 22:24:35,118 - WARNING - Not Found: /favicon.ico
2025-08-31 22:24:59,401 - INFO - Processing PDF upload request
2025-08-31 22:25:00,356 - extractor.utils.extractor - ERROR - Error processing page 2 in /code/media/uploads/DFIPL-WNEL-001-S1_ZIVVWQh.pdf: 'NoneType' object has no attribute 'replace'
2025-08-31 22:25:25,063 - extractor.utils.extractor - ERROR - Error processing page 22 in /code/media/uploads/DFIPL-WNEL-001-S1_ZIVVWQh.pdf: 'NoneType' object has no attribute 'replace'
2025-08-31 22:25:25,182 - extractor.utils.extractor - ERROR - Error processing page 23 in /code/media/uploads/DFIPL-WNEL-001-S1_ZIVVWQh.pdf: 'NoneType' object has no attribute 'replace'
2025-08-31 22:31:00,582 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 22:31:31,287 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 22:34:27,430 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 22:35:03,307 - WARNING - Not Found: /favicon.ico
2025-08-31 22:35:36,332 - INFO - Processing PDF upload request
2025-08-31 22:35:37,094 - extractor.utils.extractor - ERROR - Error processing page 2 in /code/media/uploads/DFIPL-WNEL-001-S1_b8HP4Mr.pdf: 'NoneType' object has no attribute 'replace'
2025-08-31 22:35:58,996 - extractor.utils.extractor - ERROR - Error processing page 22 in /code/media/uploads/DFIPL-WNEL-001-S1_b8HP4Mr.pdf: 'NoneType' object has no attribute 'replace'
2025-08-31 22:35:59,095 - extractor.utils.extractor - ERROR - Error processing page 23 in /code/media/uploads/DFIPL-WNEL-001-S1_b8HP4Mr.pdf: 'NoneType' object has no attribute 'replace'
2025-08-31 22:37:03,886 - INFO - /code/extractor/models.py changed, reloading.
2025-08-31 22:37:22,570 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 22:38:49,691 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 22:39:58,956 - WARNING - Not Found: /favicon.ico
2025-08-31 22:40:07,613 - WARNING - Not Found: /favicon.ico
2025-08-31 22:40:20,233 - INFO - Processing PDF upload request
2025-08-31 22:40:20,927 - extractor.utils.extractor - ERROR - Error processing page 2 in /code/media/uploads/DFIPL-WNEL-001-S1_2hvEpoN.pdf: 'NoneType' object has no attribute 'replace'
2025-08-31 22:40:43,907 - extractor.utils.extractor - ERROR - Error processing page 22 in /code/media/uploads/DFIPL-WNEL-001-S1_2hvEpoN.pdf: 'NoneType' object has no attribute 'replace'
2025-08-31 22:40:45,181 - extractor.utils.extractor - ERROR - Error processing page 23 in /code/media/uploads/DFIPL-WNEL-001-S1_2hvEpoN.pdf: 'NoneType' object has no attribute 'replace'
2025-08-31 22:44:21,014 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 22:45:03,432 - INFO - /code/extractor/templatetags/extractor_filters.py changed, reloading.
2025-08-31 22:45:27,546 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 22:46:23,857 - INFO - /code/extractor/templatetags/extractor_filters.py changed, reloading.
2025-08-31 22:46:27,497 - WARNING - Not Found: /favicon.ico
2025-08-31 22:47:00,096 - INFO - Processing PDF upload request
2025-08-31 22:49:15,472 - WARNING - Not Found: /favicon.ico
2025-08-31 22:50:16,002 - INFO - Processing PDF upload request
2025-08-31 22:50:16,637 - extractor.utils.extractor - ERROR - Error processing page 2 in /code/media/uploads/DFIPL-WNEL-001-S1.pdf: 'NoneType' object has no attribute 'replace'
2025-08-31 22:50:40,977 - extractor.utils.extractor - ERROR - Error processing page 22 in /code/media/uploads/DFIPL-WNEL-001-S1.pdf: 'NoneType' object has no attribute 'replace'
2025-08-31 22:50:41,104 - extractor.utils.extractor - ERROR - Error processing page 23 in /code/media/uploads/DFIPL-WNEL-001-S1.pdf: 'NoneType' object has no attribute 'replace'
2025-08-31 22:57:21,311 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 22:58:22,030 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 22:59:15,262 - INFO - Processing PDF upload request
2025-08-31 22:59:27,050 - INFO - Processing PDF upload request
2025-08-31 23:01:53,116 - WARNING - Not Found: /favicon.ico
2025-08-31 23:02:15,062 - INFO - Processing PDF upload request
2025-08-31 23:02:15,191 - WARNING - Not Found: /favicon.ico
2025-08-31 23:02:28,531 - WARNING - Not Found: /favicon.ico
2025-08-31 23:02:50,225 - INFO - Processing PDF upload request
2025-08-31 23:05:44,529 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 23:07:56,250 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 23:08:00,133 - WARNING - Not Found: /favicon.ico
2025-08-31 23:08:16,838 - INFO - Processing PDF upload request
2025-08-31 23:10:02,927 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 23:10:17,421 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 23:10:34,308 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 23:10:47,697 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 23:11:52,144 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 23:11:58,119 - WARNING - Not Found: /favicon.ico
2025-08-31 23:12:09,598 - INFO - Processing PDF upload request
2025-08-31 23:16:14,124 - INFO - /code/extractor/utils/extractor.py changed, reloading.
2025-08-31 23:16:27,155 - INFO - /code/extractor/utils/extractor.py changed, reloading.
2025-08-31 23:16:48,605 - INFO - /code/extractor/tasks.py changed, reloading.
2025-08-31 23:17:02,572 - INFO - /code/extractor/tasks.py changed, reloading.
2025-08-31 23:18:05,929 - WARNING - Not Found: /favicon.ico
2025-08-31 23:18:16,617 - INFO - /code/extractor/tasks.py changed, reloading.
2025-08-31 23:21:16,694 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 23:22:46,078 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 23:23:37,504 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 23:24:38,789 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 23:24:54,104 - INFO - /code/extractor/views.py changed, reloading.
2025-08-31 23:25:17,514 - WARNING - Not Found: /favicon.ico
2025-08-31 23:25:24,389 - WARNING - Not Found: /favicon.ico
2025-08-31 23:25:36,328 - INFO - Processing PDF upload request
2025-08-31 23:25:48,724 - INFO - Processing PDF upload request
2025-08-31 23:25:48,954 - extractor.utils.extractor - ERROR - Error processing page 1 in /code/media/uploads/Copy_of_TN09_S5.pdf: 'NoneType' object has no attribute 'replace'
2025-08-31 23:25:49,972 - WARNING - Not Found: /api/clear-task-id/
2025-08-31 23:32:07,359 - WARNING - Not Found: /favicon.ico
2025-08-31 23:32:18,375 - WARNING - Not Found: /favicon.ico
2025-08-31 23:32:22,806 - WARNING - Not Found: /favicon.ico
2025-08-31 23:38:13,976 - INFO - Processing PDF upload request
2025-08-31 23:38:31,856 - INFO - Processing PDF upload request
2025-08-31 23:42:31,871 - WARNING - Not Found: /favicon.ico
2025-08-31 23:44:31,112 - WARNING - Not Found: /api/clear-task-id/
2025-08-31 23:46:22,871 - WARNING - Not Found: /favicon.ico
2025-08-31 23:46:35,656 - WARNING - Not Found: /favicon.ico
2025-08-31 23:54:53,792 - WARNING - Not Found: /favicon.ico
2025-08-31 23:55:08,958 - INFO - Processing PDF upload request
2025-08-31 23:59:31,566 - WARNING - Not Found: /favicon.ico
2025-09-01 00:00:24,149 - WARNING - Not Found: /favicon.ico
2025-09-01 00:01:42,399 - INFO - /code/extractor_project/settings.py changed, reloading.
2025-09-01 00:03:01,792 - INFO - /code/extractor_project/settings.py changed, reloading.
2025-09-01 00:03:09,766 - WARNING - Not Found: /favicon.ico
2025-09-01 00:03:17,971 - WARNING - Not Found: /favicon.ico
